# Generated by Django 6.1 on 2026-08-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=10)),
                ('temperature', models.FloatField()),
                ('feels_like', models.FloatField()),
                ('humidity', models.PositiveIntegerField()),
                ('pressure', models.PositiveIntegerField()),
                ('weather_description', models.CharField(max_length=255)),
                ('wind_speed', models.FloatField()),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-collected_at'],
            },
        ),
    ]
